### ISSUE TITLE
Setting the frame rate for vimbax driver

### ISSUE THREAD

**Issue by Masrur02** [alliedvision/vimbax_ros2_driver#5]
Hi, 
Previously I got this error:
> feature_float_get failed with error -3 
The solution for that was commenting out this block of code:
```
auto const frame_rate = feature_float_get(SFNCFeatures::AcquisitionFrameRate);
  if (!frame_rate) {
    if (frame_rate.error().code != VmbErrorNotAvailable) {
      return frame_rate.error();
    }
  } else {
    info.frame_rate = *frame_rate;
  }
```
because 
> At the Mako camera series the feature for read the current frame rate is not called "AcquisitionFrameRate". The get_camera_info function tries to always read this feature and fails, because it is not available. As get_camera_info is called during initialization the node startup fails. 

One community member in issue 1 suggested that to
> You can use the following changes to fix the issue: https://github.com/alliedvision/vimbax_ros2_driver/commit/bca291816d592296be690f2889ef8179837da4f3
> Please be aware that this disables the frame rate read out and therefore also the camera info service will not return a valid value for the frame rate.

However, now my question is if we disable the readout of the frame rate. How can we get the current frame rate and how can I set a desired frame rate? Moreover is there any brief documentation on how to play with the camera's parameters like width, height, frame rate, and so on?

**Comment by Teresa-AlliedVision** [comment]
Hi, as mentioned by Dennis, the Mako cameras use a different feature name set. If you are not very familiar with GenICam conventions, this will hopefully fill the gap.

## Feature Naming
SFNC is the "Standard Feature Naming Convention" for GenICam cameras. The Mako cameras are an older model line, so they use an older version of SFNC. The convenience functions in this ROS2 implementation are compatible with the newer camera line Alvium, with  newer SFNC.
[Mako/Manta/Prosilica Feature Reference](https://cdn.alliedvision.com/fileadmin/content/documents/products/cameras/various/features/GigE_Features_Reference.pdf)
[Alvium Feature Reference](https://cdn.alliedvision.com/fileadmin/content/documents/products/cameras/various/features/Alvium_Features_Reference.pdf)

## Accessing Features by Name
Of course you can still use the older SFNC, just specify the correct feature name and exclude the convenience function. 
Please reference the examples on how to [access features](https://github.com/alliedvision/vimbax_ros2_driver/blob/main/vimbax_camera_examples/vimbax_camera_examples/feature_get.py) and [read out the information](https://github.com/alliedvision/vimbax_ros2_driver/blob/main/vimbax_camera_examples/vimbax_camera_examples/feature_info_get.py).

## Where to find more Camera Documentation
All of the information and downloads available are on the Allied Vision website, organized by model family.
Direct links to documentation:

- [Alvium USB](https://www.alliedvision.com/de/support/technische-dokumentation/alvium-usb-downloads/) 
- [Alvium GigE](https://www.alliedvision.com/de/support/technische-dokumentation/alvium-gige-downloads/)
- [Alvium CSI](https://www.alliedvision.com/de/support/technische-dokumentation/alvium-csi-2-downloads/)
- [Manta](https://www.alliedvision.com/de/support/technische-dokumentation/manta-downloads/)
- [Mako](https://www.alliedvision.com/de/support/technische-dokumentation/mako-downloads/)
- [Prosilica GT](https://www.alliedvision.com/de/support/technische-dokumentation/prosilica-gt-downloads/)
